server:
  port: 8080

  # mysql
spring:
  datasource:
    url: jdbc:mysql://192.168.2.6:3306/boran?useunicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true
    username: root
    password: boran123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update
entitymanager:
  packagesToScan: com.boran.Entity